---
name: Net-IP-Match-Regexp
version: 0.94
author:
  - 'Clotho Advanced Media, Inc. <cpan@clotho.com>'
abstract: Efficiently match IP addresses against ranges
license: perl
resources:
  license: perl://dev.perl.org/licenses/
requires:
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Net::IP::Match::Regexp:
    file: lib/Net/IP/Match/Regexp.pm
    version: 0.94
generated_by: Module::Build version 0.2706
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
